### PR TITLE
[WIP] Remove duplicates from subscribed metrics, metric per resource #51

### LINKED ISSUE #51: Libvirt
Snap daemon version:1.0.0
Hardware configuration: Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz, 32G RAM
OS: Ubuntu 16.04.1 LTS
Kernel: Linux 4.4.0-57-generic x86_64 GNU/Linux
Relevant tools: Libvirt
We have 2 vm's configured in the host, where they are vyatta 5600 vRouter,
where the vm's inter-communication is by Linux bridge taps.

**What happened**:
We have updated to libvirt v12, 
and are encountering several problems:
1. Metrics from all possible vm's in host are measured, with no regards to what is written in the task json file used to create the task.
For instance, the json manifest file contains metrics that are related only to a single vm, yet in the metrics measured by the task we see metrics from other vm's as well.
In the command "snaptel metric list" we indeed see that the format has changed,
and there is no-backward compatibility (to as was in v8).
This is a huge drawback to us, as the entire task creation mechanism we developed was written on a per -VM basis (for optimization matters).

2. The same metrics are measured twice (seen in task watch).

**What you expected to happen**:
1. Only the metrics given in the manifest file should be measured
2. These metrics should be measured once (and appear so in the task watch)

**Steps to reproduce it** (as minimally and precisely as possible):

1. Create a host with 2 vm's (of some type )
2. Create a task that applies only to a single vm metrics
3. 

**Anything else do we need to know** (e.g. issue happe
[vm1_forwarding_libvirt.txt](https://github.com/intelsdi-x/snap-plugin-collector-libvirt/files/801990/vm1_forwarding_libvirt.txt)

*The manifest file is attached.

sudo virsh list:
 Id    Name                           State
----------------------------------------------------
 5     l3fwd-1                        running
 6     l3fwd-2                        running

### PR DESCRIPTION
**Pull request by sandlbn**
Fixes #51 

Summary of changes:

-   [x]  Remove duplicates from subscribed metric list
-   [x] Add possibility to subscribe metric per resource (nic, disk, cpu)

How to verify it:
- Run tests

Testing done:
-  Unit test

### CODE REVIEW

File: libvirtcollector/common.go [hunk 1]
```diff
@@ -65,3 +67,31 @@ func copyNamespaceElements(ns []plugin.NamespaceElement) []plugin.NamespaceEleme
...
 }
+
+func removeDuplicates(elements []plugin.Metric) []plugin.Metric {
+	// Use map to record duplicates as we find them.
+	encountered := map[string]bool{}
+	result := []plugin.Metric{}
+
+	for _, v := range elements {
+		ns := joinNamespace(v.Namespace.Strings())
+		if encountered[ns] == true {
```
Comment (PatrykMatyjasek) [inline libvirtcollector/common.go]: maybe you should invert condition? 
if !encoutered[ns]

**Comment by nanliu** [comment]
Could you also increment the version number? We can cut a new release once this is merged. Thanks!

File: libvirtcollector/common.go [hunk 2]
```diff
@@ -65,3 +67,27 @@ func copyNamespaceElements(ns []plugin.NamespaceElement) []plugin.NamespaceEleme
...
 }
+
+func removeDuplicates(elements []plugin.Metric) []plugin.Metric {
+	// Use map to record duplicates as we find them.
+	encountered := map[string]bool{}
+	result := []plugin.Metric{}
+
+	for _, v := range elements {
+		ns := joinNamespace(v.Namespace.Strings())
+		if !encountered[ns] == true {
```
Comment (PatrykMatyjasek) [inline libvirtcollector/common.go]: You don't need to compare with true.
```
if !encountered[ns]
```
is enough :)

**Comment by PatrykMatyjasek** [comment]
LGTM

File: libvirtcollector/common.go [hunk 3]
```diff
@@ -65,3 +78,74 @@ func copyNamespaceElements(ns []plugin.NamespaceElement) []plugin.NamespaceEleme
...
+		}
+	}
+	// Return the new slice.
+	return result
+}
+
+func metricStored(elements []plugin.Metric, newNamespace []plugin.NamespaceElement) bool {
+	for _, v := range elements {
+		ns := joinNamespace(v.Namespace.Strings())
+		fmt.Println(joinNamespaceElements(newNamespace))
```
Comment (PatrykMatyjasek) [inline libvirtcollector/common.go]: are those prints necessary?

File: libvirtcollector/common.go [hunk 4]
```diff
@@ -65,3 +78,74 @@ func copyNamespaceElements(ns []plugin.NamespaceElement) []plugin.NamespaceEleme
...
+			result = append(result, v)
+		}
+	}
+	// Return the new slice.
+	return result
+}
+
+func metricStored(elements []plugin.Metric, newNamespace []plugin.NamespaceElement) bool {
+	for _, v := range elements {
+		ns := joinNamespace(v.Namespace.Strings())
```
Comment (PatrykMatyjasek) [inline libvirtcollector/common.go]: instead of implement function You can use strings.Join(v.Namespace.Strings(), "/")

File: libvirtcollector/libvirtcollector_test.go [hunk 5]
```diff
@@ -96,6 +100,27 @@ func TestLibirtPlugin(t *testing.T) {
...
+		}
+		mts := []plugin.Metric{}
+
+		mts = append(mts, plugin.Metric{Namespace: plugin.NewNamespace(Vendor, Plugin).AddDynamicElement("domain_id", "an id of libvirt domain").AddStaticElement("cpu").AddDynamicElement("cpu_id", "id of vcpu").AddStaticElement("cputime"), Config: config})
+		mts = append(mts, plugin.Metric{Namespace: plugin.NewNamespace(Vendor, Plugin).AddDynamicElement("domain_id", "an id of libvirt domain").AddStaticElement("cpu").AddDynamicElement("cpu_id", "id of vcpu").AddStaticElement("cputime"), Config: config})
+		mts = append(mts, plugin.Metric{Namespace: plugin.NewNamespace(Vendor, Plugin).AddDynamicElement("domain_id", "an id of libvirt domain").AddStaticElements("cpu", "cputime"), Config: config})
+		mts = append(mts, plugin.Metric{Namespace: plugin.NewNamespace(Vendor, Plugin).AddDynamicElement("domain_id", "an id of libvirt domain").AddStaticElements("cpu", "cputime"), Config: config})
+		metrics, err := libvirtCol.CollectMetrics(mts)
+		for _, m := range metrics {
+			fmt.Println(m.Namespace.Strings())
```
Comment (PatrykMatyjasek) [inline libvirtcollector/libvirtcollector_test.go]: i think it is not necessary here
